#!/usr/bin/env bash
# bash script that automatically configures ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
service nginx start

echo "Hello World!" >  /var/www/html/index.html

cat << 'EOF' > /etc/nginx/sites-available/default
# Defualt server configuration
#
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=-BE6GyHcASE;
	}

	location / {
		try_files $uri $uri/ =404;
	}
}
EOF

# Apply changed configurations
service nginx restart
