#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains


balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 253588-web-01 34.207.64.138.80 check
    server 253588-web-02 100.26.155.167.80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
