#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains

sudo apt-get -y update

sudo apt-get -y install software-properties-common

sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 253588-web-01 34.207.64.138.80 check
    server 253588-web-02 100.26.155.167.80 check
"
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
